version: 1.2
workflows:
   - subclass: CWL
     name: autopotato-attack
     primaryDescriptorPath: /potato.cwl
     authors:
       - name: Denis Yuen
         orcid: 0000-0002-6130-1021
       - name: UCSC Genomics Institute
         role: Institute
         affiliation: UCSC
     publish: True
     testParameterFiles:
         - /test/dockstore.cwl.json

